In [1]:
import pandas as pd
import numpy as np

In [3]:
#Load datasets
df_bio = pd.read_csv('TARA_BIO.csv')
df_meso = pd.read_csv('TARA_meso.csv')
df_nut = pd.read_csv('TARA_NUT.csv')
df_depth = pd.read_csv('TARA_DEPTH.csv')

In [4]:
df_bio.columns = df_bio.columns.str.lower()
df_meso.columns = df_meso.columns.str.lower()
df_nut.columns = df_nut.columns.str.lower()
df_depth.columns = df_depth.columns.str.lower()

In [5]:
new_column_names_bio = {'sample id (tara_barcode#)':'sample_id', 'station (tara_station#)':'tara_station', 'env feature (full name (envo:id), terms re...)':'env feature'}
df_bio = df_bio.rename(columns=new_column_names_bio)

In [10]:
df_bio.isnull().sum()/34768*100

sample_id                                                  0.000000
campaign                                                   0.132306
tara_station                                               0.000000
event                                                      0.000000
env feature (abbreviation)                                 0.000000
env feature                                                0.000000
species div (originally reported as shanno...)            45.446963
species div (originally reported as shanno...).1          45.446963
species div (originally reported as shanno...).2          45.446963
species div (originally reported as shanno...).3          45.446963
species div (originally reported as shanno...).4          46.396111
species div (originally reported as shanno...).5          44.028992
species div (originally reported as mitag....)            78.618270
species div (originally reported as mitag....).1          78.618270
species div (originally reported as mitag....).2          78.618270
s (originally reported as mitag....)                      78.618270
wfdc (originally reported as mitag....)                   78.618270
functional richness (originally reported as og.ric...)    78.618270
feve (originally reported as og.eve...)                   78.618270
dtype: float64

In [11]:
new_column_names_meso = {'sample id (tara_barcode#)':'sample_id', 'campaign (tara_event-datetime_station#_...)':'campaign', 'station (tara_station#)':'tara_station', 'event (tara_event-datetime_station#_...)':'event', 'date/time (tara_event-datetime_station#_...)':'date/time', 'latitude (tara_event-datetime_station#_...)':'latitude', 'longitude (tara_event-datetime_station#_...)':'longitude'}
df_meso = df_meso.rename(columns=new_column_names_meso)

In [18]:
df_meso.isnull().sum().nlargest(10)/34768*100

npp c [mg/m**2/day] (at the sampling location and ...)    98.469857
ssfcdom [ppb (qse)] (at the sampling location and ...)    84.603659
latitude (of the continental shelf with...)               65.281293
longitude (of the continental shelf with...)              65.281293
npp c [mg/m**2/day] (at the sampling location for ...)    62.666820
latitude (of the geographic coordinate ...)               30.387138
longitude (of the geographic coordinate ...)              30.387138
tss [mg/l] (at the sampling location for ...)             29.328693
pic [mol/m**3] (at the sampling location for ...)         26.650943
poc [âµg/kg] (at the sampling location for ...)           22.212954
dtype: float64

In [21]:
df_meso[df_meso['Sample ID (TARA_barcode#)'] == 'TARA_X000000174']

,Sample ID (TARA_barcode#),Campaign (TARA_event-datetime_station#_...),Station (TARA_station#),Event (TARA_event-datetime_station#_...),Date/Time (TARA_event-datetime_station#_...),Latitude (TARA_event-datetime_station#_...),Longitude (TARA_event-datetime_station#_...),Env feature ([abbreviation] description (E...),Depth nominal (of the environmental feature),Sample method (protocol-label_size-fraction),...,u [cm/s] (at the sampling location and ...),v [cm/s] (at the sampling location and ...),OW (at the sampling location and ...),MLE [1/day] (at the sampling location and ...),RT [days] (of the water mass at the samp...),Latitude+ (of the continental shelf with...),Longitude+ (of the continental shelf with...),Age [days] (number of days since the samp...),Latitude+ (of the geographic coordinate ...),Longitude+ (of the geographic coordinate ...)
31899,TARA_X000000174,TARA_20090905Z,TARA_001,TARA_20090907T1530Z_001_EVENT_NET,2009-09-07T15:30,44.4013,-9.8273,[ZZZ] marine water layer (ENVO:01000295),0-500,IMG-(formol)_N>300,...,-3.855836,-8.864694,-0.11994,0.075851,10.972222,NaN,NaN,>120,44.483,-10.3488

In [20]:
df_nut.isnull().sum().nlargest(10)/34768*100

nitrate and nitrite      20.734584
nitrate and nitrite.1    20.734584
nitrate and nitrite.2    20.734584
nitrate and nitrite.3    20.734584
nitrate and nitrite.4    20.734584
phosphate                18.911068
phosphate.1              18.911068
phosphate.2              18.911068
phosphate.3              18.911068
phosphate.4              18.911068
dtype: float64

In [11]:
df_nut_small = df_nut.drop(['sample id.1', 'sample id.2'], axis = 'columns')
new_column_names_nut = {'sample id': 'sample_id'}
df_nut_small = df_nut_small.rename(columns=new_column_names_nut)
df_nut_small

,parameter,sample_id,station label,event label,environmental feature,"depth, nominal","depth, top/min","depth, bottom/max","size fraction, lower threshold","size fraction, upper threshold",...,nitrate and nitrite,nitrate and nitrite.1,nitrate and nitrite.2,nitrate and nitrite.3,nitrate and nitrite.4,silicate,silicate.1,silicate.2,silicate.3,silicate.4
0,1,TARA_X000000174,TARA_001,TARA_20090907T1530Z_001_EVENT_NET,[ZZZ] marine water layer (ENVO:01000295),0-500,0.0,500.0,300,>300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,TARA_X000000173,TARA_001,TARA_20090907T1610Z_001_EVENT_NET,[SRF] surface water layer (ENVO:00010504),9,3.0,15.0,180,>180,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,TARA_X000000172,TARA_002,TARA_20090909T1830Z_002_EVENT_NET,[ZZZ] marine water layer (ENVO:01000295),0-200,0.0,200.0,680,>680,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,TARA_X000000171,TARA_003,TARA_20090913T1130Z_003_EVENT_NET,[SRF] surface water layer (ENVO:00010504),9,3.0,15.0,300,>300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,TARA_X000000180,TARA_003,TARA_20090913T1200Z_003_EVENT_PUMP,[SRF] surface water layer (ENVO:00010504),9,3.0,15.0,<200,200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34771,34772,TARA_B010001151,TARA_999,TARA_20131205T1323Z_999_EVENT_CSSS,[SRF] surface water layer (ENVO:00010504),2,1.0,3.0,<0.7,>0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34772,34773,TARA_G100017759,TARA_999,TARA_20131205T1323Z_999_EVENT_CSSS,[SRF] surface water layer (ENVO:00010504),2,1.0,3.0,<0.7,>0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34773,34774,TARA_R010000733,TARA_999,TARA_20131206T0821Z_999_EVENT_CSSS,[SRF] surface water layer (ENVO:00010504),2,1.0,3.0,0.7,>0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34774,34775,TARA_B010001152,TARA_999,TARA_20131206T0821Z_999_EVENT_CSSS,[SRF] surface water layer (ENVO:00010504),2,1.0,3.0,<0.7,>0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34775,34776,TARA_G100017758,TARA_999,TARA_20131206T0821Z_999_EVENT_CSSS,[SRF] surface water layer (ENVO:00010504),2,1.0,3.0,<0.7,>0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
new_column_names_depth = {'sample id (tara_barcode#)':'sample_id', 'station (tara_station#)':'tara_station'}
df_depth = df_depth.rename(columns=new_column_names_depth)

In [57]:
df_depth

,sample_id,basis,campaign,tara_station,event,event 2,method/device,date/time,latitude,longitude,...,"season (early, middle, or late)",moon phase proportion (indicates if the phase of the...),moon phase proportion (indicates the proportion of i...),ssd [min] (day length),u [cm/s] (calculated (d'ovidio et al. 2...),v [cm/s] (calculated (d'ovidio et al. 2...),ow (indicates the presence of an ...),mle [1/day] (indicates the presence of a t...),sst grad h [â°c/100 km] (calculated (d'ovidio et al. 2...),rt [days] (of the water mass. values>30 ...)
0,TARA_X000000174,SV Tara,TARA_20090905Z,TARA_001,TARA_20090907T1530Z_001_EVENT_NET,[day] [water layer with no specific feature],"Plankton net, type=Bongo, mesh(Âµm)=300, mouth...",2009-09-07T15:30,44.4013,-9.8273,...,NaN,-1.0,0.92,776.0,NaN,NaN,NaN,NaN,NaN,NaN
1,TARA_X000000173,SV Tara,TARA_20090905Z,TARA_001,TARA_20090907T1610Z_001_EVENT_NET,[day] [surface water layer (ENVO:00002042)],"Plankton net+sieve, type=Double, mesh(Âµm)=20,...",2009-09-07T16:10,44.4013,-9.8273,...,NaN,-1.0,0.92,776.0,NaN,NaN,NaN,NaN,NaN,NaN
2,TARA_X000000172,SV Tara,TARA_20090905Z,TARA_002,TARA_20090909T1830Z_002_EVENT_NET,[day] [water layer with no specific feature],"Plankton net, type=Regent, mesh(Âµm)=680, mout...",2009-09-09T18:30,39.0564,-10.9808,...,NaN,-1.0,0.77,762.0,NaN,NaN,NaN,NaN,NaN,NaN
3,TARA_X000000171,SV Tara,TARA_20090913Z,TARA_003,TARA_20090913T1130Z_003_EVENT_NET,[night] [surface water layer (ENVO:00002042)] ...,"Plankton net, type=Bongo, mesh(Âµm)=300, mouth...",2009-09-13T11:30,36.7320,-10.4750,...,NaN,-1.0,0.34,750.0,NaN,NaN,NaN,NaN,NaN,NaN
4,TARA_X000000180,SV Tara,TARA_20090913Z,TARA_003,TARA_20090913T1200Z_003_EVENT_PUMP,[day] [surface water layer (ENVO:00002042)],High Volume Peristaltic Pump,2009-09-13T12:00,36.7320,-10.4750,...,3.0,-1.0,0.34,750.0,-2.571,4.705,-0.063,0.025,21.922,22.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34763,TARA_G100017759,SV Tara,TARA_20131116Z,TARA_999,TARA_20131205T1323Z_999_EVENT_CSSS,[day] [surface water layer (ENVO:00002042)] [b...,Continuous Surface Sampling System,2013-12-05T13:23,48.6007,-9.0989,...,NaN,1.0,0.09,509.0,NaN,NaN,NaN,NaN,NaN,NaN
34764,TARA_R010000734,SV Tara,TARA_20131116Z,TARA_999,TARA_20131205T1323Z_999_EVENT_CSSS,[day] [surface water layer (ENVO:00002042)] [b...,Continuous Surface Sampling System,2013-12-05T13:23,48.6007,-9.0989,...,NaN,1.0,0.09,509.0,NaN,NaN,NaN,NaN,NaN,NaN
34765,TARA_B010001152,SV Tara,TARA_20131116Z,TARA_999,TARA_20131206T0821Z_999_EVENT_CSSS,[day] [surface water layer (ENVO:00002042)] [b...,Continuous Surface Sampling System,2013-12-06T08:21,48.2609,-5.1184,...,NaN,1.0,0.17,511.0,NaN,NaN,NaN,NaN,NaN,NaN
34766,TARA_G100017758,SV Tara,TARA_20131116Z,TARA_999,TARA_20131206T0821Z_999_EVENT_CSSS,[day] [surface water layer (ENVO:00002042)] [b...,Continuous Surface Sampling System,2013-12-06T08:21,48.2609,-5.1184,...,NaN,1.0,0.17,511.0,NaN,NaN,NaN,NaN,NaN,NaN
34767,TARA_R010000733,SV Tara,TARA_20131116Z,TARA_999,TARA_20131206T0821Z_999_EVENT_CSSS,[day] [surface water layer (ENVO:00002042)] [b...,Continuous Surface Sampling System,2013-12-06T08:21,48.2609,-5.1184,...,NaN,1.0,0.17,511.0,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# Find the columns that aren't in the first DataFrame
different_cols = df_meso.columns.difference(df_bio.columns)
 
# Filter out the columns that are different.
# You could pass in the df2[diff_cols] 
# directly into the merge as well.
data_merged = df_meso[different_cols] 
# Merge the DataFrames
df_merged = pd.merge(df_bio, data_merged, left_index=True,
                     right_index=True, how='inner')

In [17]:
df_merged

,sample_id,campaign,tara_station,event,env feature (abbreviation),env feature,species div (originally reported as shanno...),species div (originally reported as shanno...).1,species div (originally reported as shanno...).2,species div (originally reported as shanno...).3,...,ssfcdom [ppb (qse)] (at the sampling location and ...),ssm index [1/s**2] (at the sampling location and ...),ssphi sat [%] (at the sampling location for ...),sst grad h [â°c/100 km] (at the sampling location and ...),sst grad h [â°c/100 km] (at the sampling location for ...),"station (tara_station#, registered at ...)","time of day (at the sampling location, dat...)",tss [mg/l] (at the sampling location for ...),u [cm/s] (at the sampling location and ...),v [cm/s] (at the sampling location and ...)
0,TARA_X000000174,TARA_20090905Z,TARA_001,TARA_20090907T1530Z_001_EVENT_NET,INT,water layer with no specific feature,NaN,NaN,NaN,NaN,...,NaN,0.000003,1.190373,0.39136,18.633288,TARA_001,day,0.146238,-3.855836,-8.864694
1,TARA_X000000173,TARA_20090905Z,TARA_001,TARA_20090907T1610Z_001_EVENT_NET,SRF,surface water layer (ENVO:00002042),NaN,NaN,NaN,NaN,...,NaN,0.000003,1.190373,0.39136,18.633288,TARA_001,day,0.146238,-3.855836,-8.864694
2,TARA_X000000172,TARA_20090905Z,TARA_002,TARA_20090909T1830Z_002_EVENT_NET,INT,water layer with no specific feature,NaN,NaN,NaN,NaN,...,NaN,0.000003,0.750963,1.34040,20.026061,TARA_002,day,0.077717,-0.631608,-0.773749
3,TARA_X000000171,TARA_20090913Z,TARA_003,TARA_20090913T1130Z_003_EVENT_NET,SRF,surface water layer (ENVO:00002042),NaN,NaN,NaN,NaN,...,NaN,0.000005,1.320878,0.42763,21.362549,TARA_003,night,0.060093,-3.196994,6.553035
4,TARA_X000000180,TARA_20090913Z,TARA_003,TARA_20090913T1200Z_003_EVENT_PUMP,SRF,surface water layer (ENVO:00002042),0.50496,0.642455,0.766421,0.7784,...,NaN,0.000005,1.320878,0.42763,21.362549,TARA_003,day,0.060093,-3.196994,6.553035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34763,TARA_G100017759,TARA_20131116Z,TARA_999,TARA_20131205T1323Z_999_EVENT_CSSS,SRF,surface water layer (ENVO:00002042),NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,12.308273,TARA_999,day,NaN,NaN,NaN
34764,TARA_R010000734,TARA_20131116Z,TARA_999,TARA_20131205T1323Z_999_EVENT_CSSS,SRF,surface water layer (ENVO:00002042),NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,TARA_999,day,NaN,NaN,NaN
34765,TARA_B010001152,TARA_20131116Z,TARA_999,TARA_20131206T0821Z_999_EVENT_CSSS,SRF,surface water layer (ENVO:00002042),NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,TARA_999,day,NaN,NaN,NaN
34766,TARA_G100017758,TARA_20131116Z,TARA_999,TARA_20131206T0821Z_999_EVENT_CSSS,SRF,surface water layer (ENVO:00002042),NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,TARA_999,day,NaN,NaN,NaN
34767,TARA_R010000733,TARA_20131116Z,TARA_999,TARA_20131206T0821Z_999_EVENT_CSSS,SRF,surface water layer (ENVO:00002042),NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,13.333583,TARA_999,day,NaN,NaN,NaN

In [19]:
# Find the columns that aren't in the first DataFrame
different_cols_nut = df_nut_small.columns.difference(df_merged.columns)
 
# Filter out the columns that are different.
# You could pass in the df2[diff_cols] 
# directly into the merge as well.
data_merged_nut = df_nut[different_cols_nut] 
# Merge the DataFrames
df_merged_nut = pd.merge(df_merged, data_merged_nut, left_index=True,
                    right_index=True, how='inner')

In [21]:
df_merged_nut

,sample_id,campaign,tara_station,event,env feature (abbreviation),env feature,species div (originally reported as shanno...),species div (originally reported as shanno...).1,species div (originally reported as shanno...).2,species div (originally reported as shanno...).3,...,sample material,sample method,silicate,silicate.1,silicate.2,silicate.3,silicate.4,"size fraction, lower threshold","size fraction, upper threshold",station label
0,TARA_X000000174,TARA_20090905Z,TARA_001,TARA_20090907T1530Z_001_EVENT_NET,INT,water layer with no specific feature,NaN,NaN,NaN,NaN,...,TARA_001_ZZZ_300->,IMG-(formol)_N>300,NaN,NaN,NaN,NaN,NaN,300,>300,TARA_001
1,TARA_X000000173,TARA_20090905Z,TARA_001,TARA_20090907T1610Z_001_EVENT_NET,SRF,surface water layer (ENVO:00002042),NaN,NaN,NaN,NaN,...,TARA_001_SRF_180->,IMG-(formol)_N>180,NaN,NaN,NaN,NaN,NaN,180,>180,TARA_001
2,TARA_X000000172,TARA_20090905Z,TARA_002,TARA_20090909T1830Z_002_EVENT_NET,INT,water layer with no specific feature,NaN,NaN,NaN,NaN,...,TARA_002_ZZZ_680->,IMG-(formol)_N>680,NaN,NaN,NaN,NaN,NaN,680,>680,TARA_002
3,TARA_X000000171,TARA_20090913Z,TARA_003,TARA_20090913T1130Z_003_EVENT_NET,SRF,surface water layer (ENVO:00002042),NaN,NaN,NaN,NaN,...,TARA_003_SRF_300->,IMG-(formol)_N>300,NaN,NaN,NaN,NaN,NaN,300,>300,TARA_003
4,TARA_X000000180,TARA_20090913Z,TARA_003,TARA_20090913T1200Z_003_EVENT_PUMP,SRF,surface water layer (ENVO:00002042),0.50496,0.642455,0.766421,0.7784,...,TARA_003_SRF_<-200,CULT-(dmso)_W<200,NaN,NaN,NaN,NaN,NaN,<200,200,TARA_003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34763,TARA_G100017759,TARA_20131116Z,TARA_999,TARA_20131205T1323Z_999_EVENT_CSSS,SRF,surface water layer (ENVO:00002042),NaN,NaN,NaN,NaN,...,TARA_999_SRF_<->,IMG-(live)_W<>,NaN,NaN,NaN,NaN,NaN,<0.7,>0.7,TARA_999
34764,TARA_R010000734,TARA_20131116Z,TARA_999,TARA_20131205T1323Z_999_EVENT_CSSS,SRF,surface water layer (ENVO:00002042),NaN,NaN,NaN,NaN,...,TARA_999_SRF_0.7->,BGC-PIGMENTS_W>0.7,NaN,NaN,NaN,NaN,NaN,0.7,>0.7,TARA_999
34765,TARA_B010001152,TARA_20131116Z,TARA_999,TARA_20131206T0821Z_999_EVENT_CSSS,SRF,surface water layer (ENVO:00002042),NaN,NaN,NaN,NaN,...,TARA_999_SRF_<->,IMG-(gluta+pfa)_W<>,NaN,NaN,NaN,NaN,NaN,<0.7,>0.7,TARA_999
34766,TARA_G100017758,TARA_20131116Z,TARA_999,TARA_20131206T0821Z_999_EVENT_CSSS,SRF,surface water layer (ENVO:00002042),NaN,NaN,NaN,NaN,...,TARA_999_SRF_<->,IMG-(live)_W<>,NaN,NaN,NaN,NaN,NaN,<0.7,>0.7,TARA_999
34767,TARA_R010000733,TARA_20131116Z,TARA_999,TARA_20131206T0821Z_999_EVENT_CSSS,SRF,surface water layer (ENVO:00002042),NaN,NaN,NaN,NaN,...,TARA_999_SRF_0.7->,BGC-PIGMENTS_W>0.7,NaN,NaN,NaN,NaN,NaN,0.7,>0.7,TARA_999

In [23]:
# Find the columns that aren't in the first DataFrame
different_cols_depth = df_depth.columns.difference(df_merged_nut.columns)
 
# Filter out the columns that are different.
# You could pass in the df2[diff_cols] 
# directly into the merge as well.
data_merged_depth = df_depth[different_cols_depth] 
data_merged_depth

,[no2]- [âµmol/l] (in the selected environmental...),[no3]- + [no2]- [âµmol/l] (in the selected environmental...),[no3]- [âµmol/l] (in the selected environmental...),[po4]3- [âµmol/l] (in the selected environmental...),bac660 [1/m] (in the selected environmental...),bacp [1/m] (in the selected environmental...),bb470 [1/m] (in the selected environmental...),bbp470 [1/m] (in the selected environmental...),beta470 [m/sr] (in the selected environmental...),beta470 [m/sr] (in the selected environmental...).1,...,sal (in the selected environmental...),"season (early, middle, or late)","season (spring, summer, autumn, or wi...)",si(oh)4 [âµmol/l] (in the selected environmental...),sigma-theta [kg/m**3] (in the selected environmental...),ssd [min] (day length),sst grad h [â°c/100 km] (calculated (d'ovidio et al. 2...),tpot [â°c] (in the selected environmental...),u [cm/s] (calculated (d'ovidio et al. 2...),v [cm/s] (calculated (d'ovidio et al. 2...)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,776.0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,776.0,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,762.0,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,750.0,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.897,3.0,2.0,NaN,25.7192,750.0,21.922,21.7913,-2.571,4.705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34763,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,509.0,NaN,NaN,NaN,NaN
34764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,509.0,NaN,NaN,NaN,NaN
34765,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,511.0,NaN,NaN,NaN,NaN
34766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,511.0,NaN,NaN,NaN,NaN
34767,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,511.0,NaN,NaN,NaN,NaN

In [47]:
def getDuplicateColumns(df):

	# Create an empty set
	duplicateColumnNames = set()

	# Iterate through all the columns of dataframe
	for x in range(df.shape[1]):

		# Take column at xth index.
		col = df.iloc[:, x]

		# Iterate through all the columns
		for y in range(x + 1, df.shape[1]):

			# Take column at yth index.
			otherCol = df.iloc[:, y]

			# Check if two columns at x & y
			if col.equals(otherCol):
				duplicateColumnNames.add(df.columns.values[y])

	return list(duplicateColumnNames)


# Driver code
if __name__ == "__main__":

	# Get list of duplicate columns
	duplicateColNames = getDuplicateColumns(df_merged_nut)

	for column in duplicateColNames:
		print('Column Name : ', column)

In [31]:
df_final = df_merged_nut.drop(['parameter', 'station label', 'event label', 'file name', 'environmental feature', 'sample code/label',
                               'sample material', 'sample method', 'env feature (abbreviation)', 'campaign', 
                               'os region ([abbreviation] full name (mrg...)'], axis = 'columns')

In [33]:
# sort a dataframe based on column names
sorted_df = df_final.sort_index(axis = 1)
 
# show the resultant Dataframe
sorted_df

,[nh4]+ [âµmol/l] (mean value at a depth of 5 m ...),[nh4]+ std dev [â±] (standard deviation value at a...),[no2]- [âµmol/l] (mean value at a depth of 5 m ...),[no2]- std dev [â±] (standard deviation value at a...),[no3]- [âµmol/l] (mean value at a depth of 5 m ...),age [days] (number of days since the samp...),basis,bathy depth [m] (at the sampling location and ...),bg province ([abbreviation] full name (mrg...),chl a conc [mg/m**2] (at the sampling location and ...),...,ssphi sat [%] (at the sampling location for ...),sst grad h [â°c/100 km] (at the sampling location and ...),sst grad h [â°c/100 km] (at the sampling location for ...),"station (tara_station#, registered at ...)",tara_station,"time of day (at the sampling location, dat...)",tss [mg/l] (at the sampling location for ...),u [cm/s] (at the sampling location and ...),v [cm/s] (at the sampling location and ...),wfdc (originally reported as mitag....)
0,0.017782,0.003814,0.033199,0.021603,0.006594,120.0,SV Tara,-4948.0,[NADR] North Atlantic Drift Province (MRGID:21...,43.1353,...,1.190373,0.39136,18.633288,TARA_001,TARA_001,day,0.146238,-3.855836,-8.864694,NaN
1,0.017782,0.003814,0.033199,0.021603,0.006594,120.0,SV Tara,-4948.0,[NADR] North Atlantic Drift Province (MRGID:21...,43.1353,...,1.190373,0.39136,18.633288,TARA_001,TARA_001,day,0.146238,-3.855836,-8.864694,NaN
2,0.019857,0.004334,0.022540,0.003445,0.004371,120.0,SV Tara,-3559.0,[NAST-E] North Atlantic Subtropical Gyral Prov...,43.6517,...,0.750963,1.34040,20.026061,TARA_002,TARA_002,day,0.077717,-0.631608,-0.773749,NaN
3,0.019621,0.001549,0.049836,0.016420,0.008997,120.0,SV Tara,-3316.0,[NAST-E] North Atlantic Subtropical Gyral Prov...,15.8978,...,1.320878,0.42763,21.362549,TARA_003,TARA_003,night,0.060093,-3.196994,6.553035,NaN
4,0.019621,0.001549,0.049836,0.016420,0.008997,120.0,SV Tara,-3316.0,[NAST-E] North Atlantic Subtropical Gyral Prov...,15.8978,...,1.320878,0.42763,21.362549,TARA_003,TARA_003,day,0.060093,-3.196994,6.553035,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34763,NaN,NaN,NaN,NaN,NaN,NaN,SV Tara,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,...,NaN,NaN,12.308273,TARA_999,TARA_999,day,NaN,NaN,NaN,NaN
34764,NaN,NaN,NaN,NaN,NaN,NaN,SV Tara,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,...,NaN,NaN,NaN,TARA_999,TARA_999,day,NaN,NaN,NaN,NaN
34765,NaN,NaN,NaN,NaN,NaN,NaN,SV Tara,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,...,NaN,NaN,NaN,TARA_999,TARA_999,day,NaN,NaN,NaN,NaN
34766,NaN,NaN,NaN,NaN,NaN,NaN,SV Tara,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,...,NaN,NaN,NaN,TARA_999,TARA_999,day,NaN,NaN,NaN,NaN
34767,NaN,NaN,NaN,NaN,NaN,NaN,SV Tara,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,...,NaN,NaN,13.333583,TARA_999,TARA_999,day,NaN,NaN,NaN,NaN

In [35]:
sorted_df.to_csv('merged.csv', index =False)