In [15]:
import pandas as pd

In [16]:
df = pd.read_csv('TARA_mhws_3.csv')
df

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,depth bathy,bg province,chlorophyll a,date/time,...,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,time of day,total suspended matter,u,v,silva_func_diversity,mhw_count,mhw_category
0,0.017782,0.003814,0.033199,0.021603,0.006594,120.0,-4948.0,[NADR] North Atlantic Drift Province (MRGID:21...,43.1353,2009-09-07T15:30,...,1.190373,0.39136,18.633288,day,0.146238,-3.855836,-8.864694,NaN,0,none
1,0.017782,0.003814,0.033199,0.021603,0.006594,120.0,-4948.0,[NADR] North Atlantic Drift Province (MRGID:21...,43.1353,2009-09-07T16:10,...,1.190373,0.39136,18.633288,day,0.146238,-3.855836,-8.864694,NaN,0,none
2,0.019857,0.004334,0.022540,0.003445,0.004371,120.0,-3559.0,[NAST-E] North Atlantic Subtropical Gyral Prov...,43.6517,2009-09-09T18:30,...,0.750963,1.34040,20.026061,day,0.077717,-0.631608,-0.773749,NaN,0,none
3,0.019621,0.001549,0.049836,0.016420,0.008997,120.0,-3316.0,[NAST-E] North Atlantic Subtropical Gyral Prov...,15.8978,2009-09-13T11:30,...,1.320878,0.42763,21.362549,night,0.060093,-3.196994,6.553035,NaN,0,none
4,0.019621,0.001549,0.049836,0.016420,0.008997,120.0,-3316.0,[NAST-E] North Atlantic Subtropical Gyral Prov...,15.8978,2009-09-13T12:00,...,1.320878,0.42763,21.362549,day,0.060093,-3.196994,6.553035,NaN,0,none
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-11-29T11:13,...,NaN,NaN,12.249180,day,NaN,NaN,NaN,NaN,0,none
4062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-01T15:38,...,NaN,NaN,12.046478,day,NaN,NaN,NaN,NaN,0,none
4063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-02T14:16,...,NaN,NaN,12.308273,day,NaN,NaN,NaN,NaN,1,Moderate
4064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-03T15:23,...,NaN,NaN,NaN,day,NaN,NaN,NaN,NaN,0,none
4065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-04T14:48,...,NaN,NaN,13.333583,day,NaN,NaN,NaN,NaN,0,none

In [17]:
no_loc = df.drop(['latitude', 'latitude.1', 'latitude.2', 'latitude.3', 'longitude', 'longitude.1', 'longitude.2', 'longitude.3'], axis = 1)
no_loc

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,depth bathy,bg province,chlorophyll a,date/time,...,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,time of day,total suspended matter,u,v,silva_func_diversity,mhw_count,mhw_category
0,0.017782,0.003814,0.033199,0.021603,0.006594,120.0,-4948.0,[NADR] North Atlantic Drift Province (MRGID:21...,43.1353,2009-09-07T15:30,...,1.190373,0.39136,18.633288,day,0.146238,-3.855836,-8.864694,NaN,0,none
1,0.017782,0.003814,0.033199,0.021603,0.006594,120.0,-4948.0,[NADR] North Atlantic Drift Province (MRGID:21...,43.1353,2009-09-07T16:10,...,1.190373,0.39136,18.633288,day,0.146238,-3.855836,-8.864694,NaN,0,none
2,0.019857,0.004334,0.022540,0.003445,0.004371,120.0,-3559.0,[NAST-E] North Atlantic Subtropical Gyral Prov...,43.6517,2009-09-09T18:30,...,0.750963,1.34040,20.026061,day,0.077717,-0.631608,-0.773749,NaN,0,none
3,0.019621,0.001549,0.049836,0.016420,0.008997,120.0,-3316.0,[NAST-E] North Atlantic Subtropical Gyral Prov...,15.8978,2009-09-13T11:30,...,1.320878,0.42763,21.362549,night,0.060093,-3.196994,6.553035,NaN,0,none
4,0.019621,0.001549,0.049836,0.016420,0.008997,120.0,-3316.0,[NAST-E] North Atlantic Subtropical Gyral Prov...,15.8978,2009-09-13T12:00,...,1.320878,0.42763,21.362549,day,0.060093,-3.196994,6.553035,NaN,0,none
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-11-29T11:13,...,NaN,NaN,12.249180,day,NaN,NaN,NaN,NaN,0,none
4062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-01T15:38,...,NaN,NaN,12.046478,day,NaN,NaN,NaN,NaN,0,none
4063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-02T14:16,...,NaN,NaN,12.308273,day,NaN,NaN,NaN,NaN,1,Moderate
4064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-03T15:23,...,NaN,NaN,NaN,day,NaN,NaN,NaN,NaN,0,none
4065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-04T14:48,...,NaN,NaN,13.333583,day,NaN,NaN,NaN,NaN,0,none

In [18]:
no_loc.to_csv('no_loc.csv', index = False)

In [19]:
df_1 = pd.read_csv('no_loc.csv')
df_1

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,depth bathy,bg province,chlorophyll a,date/time,...,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,time of day,total suspended matter,u,v,silva_func_diversity,mhw_count,mhw_category
0,0.017782,0.003814,0.033199,0.021603,0.006594,120.0,-4948.0,[NADR] North Atlantic Drift Province (MRGID:21...,43.1353,2009-09-07T15:30,...,1.190373,0.39136,18.633288,day,0.146238,-3.855836,-8.864694,NaN,0,none
1,0.017782,0.003814,0.033199,0.021603,0.006594,120.0,-4948.0,[NADR] North Atlantic Drift Province (MRGID:21...,43.1353,2009-09-07T16:10,...,1.190373,0.39136,18.633288,day,0.146238,-3.855836,-8.864694,NaN,0,none
2,0.019857,0.004334,0.022540,0.003445,0.004371,120.0,-3559.0,[NAST-E] North Atlantic Subtropical Gyral Prov...,43.6517,2009-09-09T18:30,...,0.750963,1.34040,20.026061,day,0.077717,-0.631608,-0.773749,NaN,0,none
3,0.019621,0.001549,0.049836,0.016420,0.008997,120.0,-3316.0,[NAST-E] North Atlantic Subtropical Gyral Prov...,15.8978,2009-09-13T11:30,...,1.320878,0.42763,21.362549,night,0.060093,-3.196994,6.553035,NaN,0,none
4,0.019621,0.001549,0.049836,0.016420,0.008997,120.0,-3316.0,[NAST-E] North Atlantic Subtropical Gyral Prov...,15.8978,2009-09-13T12:00,...,1.320878,0.42763,21.362549,day,0.060093,-3.196994,6.553035,NaN,0,none
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-11-29T11:13,...,NaN,NaN,12.249180,day,NaN,NaN,NaN,NaN,0,none
4062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-01T15:38,...,NaN,NaN,12.046478,day,NaN,NaN,NaN,NaN,0,none
4063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-02T14:16,...,NaN,NaN,12.308273,day,NaN,NaN,NaN,NaN,1,Moderate
4064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-03T15:23,...,NaN,NaN,NaN,day,NaN,NaN,NaN,NaN,0,none
4065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-04T14:48,...,NaN,NaN,13.333583,day,NaN,NaN,NaN,NaN,0,none

In [20]:
no_loco = df_1.drop(['u', 'v', 'distance closest', 'distance', 'depth bathy'], axis = 1).drop_duplicates(inplace = False)
no_loco

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,bg province,chlorophyll a,date/time,"depth, nominal",...,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,time of day,total suspended matter,silva_func_diversity,mhw_count,mhw_category
0,0.017782,0.003814,0.033199,0.021603,0.006594,120.0,[NADR] North Atlantic Drift Province (MRGID:21...,43.1353,2009-09-07T15:30,0-500,...,NaN,0.000003,1.190373,0.39136,18.633288,day,0.146238,NaN,0,none
1,0.017782,0.003814,0.033199,0.021603,0.006594,120.0,[NADR] North Atlantic Drift Province (MRGID:21...,43.1353,2009-09-07T16:10,9,...,NaN,0.000003,1.190373,0.39136,18.633288,day,0.146238,NaN,0,none
2,0.019857,0.004334,0.022540,0.003445,0.004371,120.0,[NAST-E] North Atlantic Subtropical Gyral Prov...,43.6517,2009-09-09T18:30,0-200,...,NaN,0.000003,0.750963,1.34040,20.026061,day,0.077717,NaN,0,none
3,0.019621,0.001549,0.049836,0.016420,0.008997,120.0,[NAST-E] North Atlantic Subtropical Gyral Prov...,15.8978,2009-09-13T11:30,9,...,NaN,0.000005,1.320878,0.42763,21.362549,night,0.060093,NaN,0,none
4,0.019621,0.001549,0.049836,0.016420,0.008997,120.0,[NAST-E] North Atlantic Subtropical Gyral Prov...,15.8978,2009-09-13T12:00,9,...,NaN,0.000005,1.320878,0.42763,21.362549,day,0.060093,NaN,0,none
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4061,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-11-29T11:13,2,...,NaN,NaN,NaN,NaN,12.249180,day,NaN,NaN,0,none
4062,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-01T15:38,2,...,NaN,NaN,NaN,NaN,12.046478,day,NaN,NaN,0,none
4063,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-02T14:16,2,...,NaN,NaN,NaN,NaN,12.308273,day,NaN,NaN,1,Moderate
4064,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-03T15:23,2,...,NaN,NaN,NaN,NaN,NaN,day,NaN,NaN,0,none
4065,NaN,NaN,NaN,NaN,NaN,NaN,[NADR] North Atlantic Drift Province (MRGID:21...,NaN,2013-12-04T14:48,2,...,NaN,NaN,NaN,NaN,13.333583,day,NaN,NaN,0,none

In [21]:
no_loco.to_csv('no_loc_updated.csv', index = False)